[profile.default]
src = "src/contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "https://rpc.sepolia.org"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" } 